---
- name: Install python-passlib
  ansible.builtin.apt:
    name: python3-passlib
    state: present
  when: nginx_htpasswd is defined

- name: Add a user to the .htpasswd file
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd
    name: '{{ item.user }}'
    password: '{{ item.password }}'
    owner: root
    group: www-data
    mode: '0640'
  with_items: '{{ nginx_htpasswd }}'
