---
galaxy_info:
  author: 'gh_1mr'
  description: Git deploy helper
  company: ZEO Alliance
  license: BSD
  min_ansible_version: '2.5'
  platforms:
    - name: Debian
  galaxy_tags:
    - git
    - ssh
    - deploy
